name: chatify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-237.0.dev <4.0.0'

dependencies:
  cupertino_icons:
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage:
  firebase_messaging:
  intl:
  ionicons:
  cached_network_image:
  awesome_notifications:
  fluttertoast:
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
