// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAYhf7-2uovCgyfde86MVw0tMBY1mRo5k',
    appId: '1:788259437251:web:01e10bf4454cffe73d8076',
    messagingSenderId: '788259437251',
    projectId: 'chattily-4a049',
    authDomain: 'chattily-4a049.firebaseapp.com',
    storageBucket: 'chattily-4a049.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmNRuUNUbPp_fSET9DHbLi-Sr_cF2jKyU',
    appId: '1:788259437251:android:e2dda1ff1ba3e3023d8076',
    messagingSenderId: '788259437251',
    projectId: 'chattily-4a049',
    storageBucket: 'chattily-4a049.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeezS1StVd6zsJ6UZWq0cTKJiF-yxc-jk',
    appId: '1:788259437251:ios:dad0e1bcbc7970fd3d8076',
    messagingSenderId: '788259437251',
    projectId: 'chattily-4a049',
    storageBucket: 'chattily-4a049.appspot.com',
    iosBundleId: 'com.singhthatcodes.chatify',
  );
}
